name: Flowers Forever
favicon: null
layout_spectrum: 0.4145549312233925
typography_spectrum: 0.11960774008184671
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.5369530194438994
  lightness: 0.5658881277777255
  saturation: 0.6111100118141621
  rhythmicContrast: 0.7742510163225234
purpose: []
